name: Update Stompy S3 Model

on:
  release:
    types: [created]
  schedule:
    - cron: "30 10 * * *"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: "stompy-s3-model"
  cancel-in-progress: true

jobs:
  publish:
    name: Update Stompy S3 Model
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Restore cache
        id: restore-cache
        uses: actions/cache/restore@v3
        with:
          path: |
            ${{ env.pythonLocation }}
            .mypy_cache/
          key: python-requirements-${{ env.pythonLocation }}-${{ github.event.pull_request.base.sha || github.sha }}
          restore-keys: |
            python-requirements-${{ env.pythonLocation }}
            python-requirements-

      - name: Install dependencies
        run: |
          pip install -e '.[dev]'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload to S3
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        run: |
          for file in stompy/*.tar.gz; do
            aws s3 cp "$file" s3://${AWS_S3_BUCKET}/$(basename "$file")
          done
          for file in stompy_arm/*.tar.gz; do
            aws s3 cp "$file" s3://${AWS_S3_BUCKET}/arm_$(basename "$file")
          done

      - name: Save cache
        uses: actions/cache/save@v3
        if: github.ref == 'refs/heads/master'
        with:
          path: |
            ${{ env.pythonLocation }}
            .mypy_cache/
          key: ${{ steps.restore-cache.outputs.cache-primary-key }}
