name: Update Stompy S3 Model

on:
  release:
    types: [created]
  schedule:
    - cron: "30 2 * * *"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: "stompy-s3-model"
  cancel-in-progress: true

jobs:
  publish:
    name: Update Stompy S3 Model
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install 'kscale-onshape-library @ git+https://github.com/kscalelabs/onshape.git@master'  # Bleeding edge

      - name: Build package
        env:
          ONSHAPE_ACCESS_KEY: ${{ secrets.ONSHAPE_ACCESS_KEY }}
          ONSHAPE_SECRET_KEY: ${{ secrets.ONSHAPE_SECRET_KEY }}
          ONSHAPE_API: ${{ secrets.ONSHAPE_API }}
        run: python -m sim.scripts.update_stompy_s3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload to S3
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        run: |
          for file in stompy/*.tar.gz; do
            aws s3 cp "$file" s3://${AWS_S3_BUCKET}/$(basename "$file")
          done
